import Head from "next/head";
import styles from "../styles/Home.module.css";
import Logo from "../public/img/MarvelLogo.png";
import Image from "next/image";
import ContentPage from "./../Components/Content";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MARVEL COMICS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <Image src={Logo} alt="Logo" width={180} height={100} />
        </div>
        <div>
          <ContentPage />
        </div>
      </main>
    </div>
  );
}
